# Production environment configuration

global:
  environment: production
  imageRegistry: ""
  imageTag: stable

api:
  replicaCount: 3
  environment: "Production"
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
  featureFlags:
    EnableAdvancedReporting: "true"
    EnableMobileBanking: "true"
  
frontend:
  replicaCount: 3
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    
gateway:
  replicaCount: 2
  
ingress:
  enabled: true
  hosts:
    - host: api.finmfb.com
      paths:
        - path: /
          pathType: Prefix
          service: gateway
          port: 80
    - host: portal.finmfb.com
      paths:
        - path: /
          pathType: Prefix
          service: frontend
          port: 80
  tls:
    - secretName: finmfb-tls
      hosts:
        - api.finmfb.com
        - portal.finmfb.com
        
networkPolicy:
  enabled: true

# Database configuration for production
database:
  enabled: true
  resources:
    limits:
      memory: 4Gi
      cpu: "4"
    requests:
      memory: 2Gi
      cpu: "2"
  storage:
    size: 50Gi

# Redis configuration for production
redis:
  enabled: true
  replicas: 3
  resources:
    limits:
      memory: 2Gi
      cpu: "2"
    requests:
      memory: 1Gi
      cpu: "1"
  storage:
    size: 20Gi

# RabbitMQ configuration for production
rabbitmq:
  enabled: true
  replicas: 3
  resources:
    limits:
      memory: 2Gi
      cpu: "2"
    requests:
      memory: 1Gi
      cpu: "1"
  storage:
    size: 20Gi

# Pod Disruption Budget for production
podDisruptionBudget:
  enabled: true
  api:
    minAvailable: 2
  frontend:
    minAvailable: 2

# Monitoring for production
monitoring:
  enabled: true
  prometheus:
    resources:
      limits:
        memory: 4Gi
        cpu: "2"
      requests:
        memory: 2Gi
        cpu: "1"
    storage:
      size: 100Gi
  grafana:
    resources:
      limits:
        memory: 2Gi
        cpu: "1"
      requests:
        memory: 1Gi
        cpu: "0.5"
    storage:
      size: 20Gi