# Development environment configuration

global:
  environment: development
  imageRegistry: ""
  imageTag: dev

api:
  replicaCount: 1
  environment: "Development"
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  autoscaling:
    enabled: false
  featureFlags:
    EnableAdvancedReporting: "false"
    EnableMobileBanking: "true"
  
frontend:
  replicaCount: 1
  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  autoscaling:
    enabled: false
    
gateway:
  replicaCount: 1
  
ingress:
  enabled: true
  hosts:
    - host: dev-api.finmfb.com
      paths:
        - path: /
          pathType: Prefix
          service: gateway
          port: 80
    - host: dev-portal.finmfb.com
      paths:
        - path: /
          pathType: Prefix
          service: frontend
          port: 80
  tls:
    - secretName: finmfb-dev-tls
      hosts:
        - dev-api.finmfb.com
        - dev-portal.finmfb.com

# Database configuration for development
database:
  enabled: true
  resources:
    limits:
      memory: 1Gi
      cpu: "1"
    requests:
      memory: 512Mi
      cpu: "0.5"
  storage:
    size: 5Gi

# Redis configuration for development
redis:
  enabled: true
  replicas: 1
  resources:
    limits:
      memory: 512Mi
      cpu: "0.5"
    requests:
      memory: 256Mi
      cpu: "0.25"
  storage:
    size: 2Gi

# RabbitMQ configuration for development
rabbitmq:
  enabled: true
  replicas: 1
  resources:
    limits:
      memory: 512Mi
      cpu: "0.5"
    requests:
      memory: 256Mi
      cpu: "0.25"
  storage:
    size: 2Gi

# Pod Disruption Budget for development
podDisruptionBudget:
  enabled: false

# Monitoring for development
monitoring:
  enabled: true
  prometheus:
    resources:
      limits:
        memory: 512Mi
        cpu: "0.5"
      requests:
        memory: 256Mi
        cpu: "0.25"
    storage:
      size: 5Gi
  grafana:
    resources:
      limits:
        memory: 512Mi
        cpu: "0.5"
      requests:
        memory: 256Mi
        cpu: "0.25"
    storage:
      size: 2Gi