using FinTech.Core.Domain.Common;
using FinTech.Core.Domain.Entities.Common;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FinTech.Core.Domain.Entities.RegulatoryReporting
{
    /// <summary>
    /// Represents a regulatory report submitted to regulatory authorities
    /// </summary>
    public class RegulatoryReport : BaseEntity, IAuditable
    {
        [Required]
        [MaxLength(100)]
        public string ReportCode { get; set; } = string.Empty;
        
        [Required]
        [MaxLength(200)]
        public string ReportName { get; set; } = string.Empty;
        
        [MaxLength(1000)]
        public string? Description { get; set; }
        
        [Required]
        [MaxLength(100)]
        public string RegulatoryAuthority { get; set; } = string.Empty;
        
        [Required]
        [MaxLength(50)]
        public string ReportType { get; set; } = string.Empty; // Monthly, Quarterly, Annual, Ad-hoc
        
        [Required]
        public DateTime ReportingPeriodStart { get; set; }
        
        [Required]
        public DateTime ReportingPeriodEnd { get; set; }
        
        [Required]
        public DateTime DueDate { get; set; }
        
        public DateTime? SubmittedDate { get; set; }
        
        [MaxLength(50)]
        public string Status { get; set; } = "Draft"; // Draft, InReview, Approved, Submitted, Accepted, Rejected
        
        [MaxLength(20)]
        public string Version { get; set; } = "1.0";
        
        public string? PreparedBy { get; set; }
        
        public string? ReviewedBy { get; set; }
        
        public string? ApprovedBy { get; set; }
        
        public DateTime? ReviewedDate { get; set; }
        
        public DateTime? ApprovedDate { get; set; }
        
        [MaxLength(255)]
        public string? FilePath { get; set; }
        
        [MaxLength(100)]
        public string? FileFormat { get; set; } // PDF, XML, CSV, Excel
        
        public long? FileSizeBytes { get; set; }
        
        [MaxLength(64)]
        public string? FileHash { get; set; }
        
        [MaxLength(100)]
        public string? SubmissionReference { get; set; }
        
        [MaxLength(100)]
        public string? RegulatoryReference { get; set; }
        
        [MaxLength(1000)]
        public string? Comments { get; set; }
        
        [MaxLength(1000)]
        public string? RejectionReason { get; set; }
        
        public bool IsAmendment { get; set; }
        
        public string? OriginalReportId { get; set; }
        public RegulatoryReport? OriginalReport { get; set; }
        
        [MaxLength(50)]
        public string Priority { get; set; } = "Normal"; // Low, Normal, High, Critical
        
        public bool IsAutoGenerated { get; set; }
        
        [MaxLength(100)]
        public string? GenerationSource { get; set; }
        
        [Column(TypeName = "decimal(18,2)")]
        public decimal? TotalAmount { get; set; }
        
        public int? RecordCount { get; set; }
        
        [MaxLength(50)]
        public string? Currency { get; set; }
        
        [MaxLength(1000)]
        public string? ValidationErrors { get; set; }
        
        [MaxLength(2000)]
        public string? AdditionalData { get; set; } // JSON for additional metadata
        
        public DateTime? ValidationDate { get; set; }
        
        public bool IsValidated { get; set; }
        
        // Navigation properties
        public virtual ICollection<RegulatoryReportSubmission> Submissions { get; set; } = new List<RegulatoryReportSubmission>();
        public virtual ICollection<RegulatoryReportAttachment> Attachments { get; set; } = new List<RegulatoryReportAttachment>();
        public virtual ICollection<RegulatoryReportValidation> Validations { get; set; } = new List<RegulatoryReportValidation>();
        public virtual ICollection<RegulatoryReportData> ReportData { get; set; } = new List<RegulatoryReportData>();
    }

    /// <summary>
    /// Represents regulatory report submission history
    /// </summary>
    public class RegulatoryReportSubmissionHistory : BaseEntity, IAuditable
    {
        [Required]
        public string RegulatoryReportId { get; set; } = string.Empty;
        public RegulatoryReport? RegulatoryReport { get; set; }
        
        [Required]
        [MaxLength(50)]
        public string Action { get; set; } = string.Empty; // Created, Modified, Submitted, Approved, Rejected
        
        [Required]
        public DateTime ActionDate { get; set; }
        
        [Required]
        public string PerformedBy { get; set; } = string.Empty;
        
        [MaxLength(1000)]
        public string? Comments { get; set; }
        
        [MaxLength(50)]
        public string? PreviousStatus { get; set; }
        
        [MaxLength(50)]
        public string? NewStatus { get; set; }
        
        [MaxLength(2000)]
        public string? AdditionalData { get; set; } // JSON for additional context
    }
}