{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.monitoring.namespace | default "finmfb-monitoring" }}
  labels:
    {{- include "finmfb.labels" . | nindent 4 }}
    component: monitoring
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: {{ .Values.monitoring.namespace | default "finmfb-monitoring" }}
  labels:
    {{- include "finmfb.labels" . | nindent 4 }}
    component: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'finmfb-api'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - {{ .Release.Namespace }}
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app, __meta_kubernetes_pod_label_component]
            regex: {{ include "finmfb.name" . }};api
            action: keep
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: kubernetes_pod_name
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: {{ .Values.monitoring.namespace | default "finmfb-monitoring" }}
  labels:
    {{- include "finmfb.labels" . | nindent 4 }}
    component: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "finmfb.selectorLabels" . | nindent 6 }}
      component: prometheus
  template:
    metadata:
      labels:
        {{- include "finmfb.selectorLabels" . | nindent 8 }}
        component: prometheus
    spec:
      containers:
      - name: prometheus
        image: "{{ .Values.monitoring.prometheus.image.repository }}:{{ .Values.monitoring.prometheus.image.tag }}"
        imagePullPolicy: {{ .Values.monitoring.prometheus.image.pullPolicy }}
        args:
          - "--config.file=/etc/prometheus/prometheus.yml"
          - "--storage.tsdb.path=/prometheus"
          - "--web.console.libraries=/usr/share/prometheus/console_libraries"
          - "--web.console.templates=/usr/share/prometheus/consoles"
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus/
        - name: prometheus-storage
          mountPath: /prometheus
        resources:
          {{- toYaml .Values.monitoring.prometheus.resources | nindent 10 }}
      volumes:
      - name: prometheus-config
        configMap:
          name: prometheus-config
      - name: prometheus-storage
        persistentVolumeClaim:
          claimName: prometheus-storage-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-storage-claim
  namespace: {{ .Values.monitoring.namespace | default "finmfb-monitoring" }}
  labels:
    {{- include "finmfb.labels" . | nindent 4 }}
    component: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.monitoring.prometheus.storage.storageClass | default "standard" }}
  resources:
    requests:
      storage: {{ .Values.monitoring.prometheus.storage.size }}
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: {{ .Values.monitoring.namespace | default "finmfb-monitoring" }}
  labels:
    {{- include "finmfb.labels" . | nindent 4 }}
    component: prometheus
spec:
  ports:
  - port: 9090
    targetPort: 9090
    name: http
  selector:
    {{- include "finmfb.selectorLabels" . | nindent 4 }}
    component: prometheus
{{- end }}