{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "finmfb.fullname" . }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "finmfb.labels" . | nindent 4 }}
    component: redis
spec:
  selector:
    matchLabels:
      {{- include "finmfb.selectorLabels" . | nindent 6 }}
      component: redis
  serviceName: {{ include "finmfb.fullname" . }}-redis
  replicas: {{ .Values.redis.replicas }}
  template:
    metadata:
      labels:
        {{- include "finmfb.selectorLabels" . | nindent 8 }}
        component: redis
    spec:
      containers:
      - name: redis
        image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
        imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
        command:
        - redis-server
        - "--requirepass"
        - "$(REDIS_PASSWORD)"
        ports:
        - containerPort: 6379
          name: redis
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "finmfb.fullname" . }}-redis-secret
              key: redis-password
        resources:
          {{- toYaml .Values.redis.resources | nindent 10 }}
        volumeMounts:
        - name: redis-data
          mountPath: /data
        livenessProbe:
          exec:
            command:
            - redis-cli
            - -a
            - "$(REDIS_PASSWORD)"
            - ping
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - redis-cli
            - -a
            - "$(REDIS_PASSWORD)"
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
      securityContext:
        fsGroup: 999
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.redis.storage.storageClass }}
      resources:
        requests:
          storage: {{ .Values.redis.storage.size }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "finmfb.fullname" . }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "finmfb.labels" . | nindent 4 }}
    component: redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  selector:
    {{- include "finmfb.selectorLabels" . | nindent 4 }}
    component: redis
{{- end }}