apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: finmfb-monitoring
  labels:
    app: finmfb
    component: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finmfb
      component: grafana
  template:
    metadata:
      labels:
        app: finmfb
        component: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_USER
          value: "admin"
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grafana-secret
              key: admin-password
        - name: GF_INSTALL_PLUGINS
          value: "grafana-clock-panel,grafana-simple-json-datasource"
        volumeMounts:
        - name: grafana-storage
          mountPath: /var/lib/grafana
        - name: grafana-datasources
          mountPath: /etc/grafana/provisioning/datasources
        - name: grafana-dashboards
          mountPath: /etc/grafana/provisioning/dashboards
        resources:
          limits:
            memory: 1Gi
            cpu: "1"
          requests:
            memory: 512Mi
            cpu: "0.5"
      volumes:
      - name: grafana-storage
        persistentVolumeClaim:
          claimName: grafana-storage-claim
      - name: grafana-datasources
        configMap:
          name: grafana-datasources
      - name: grafana-dashboards
        configMap:
          name: grafana-dashboards
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-storage-claim
  namespace: finmfb-monitoring
  labels:
    app: finmfb
    component: grafana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: finmfb-monitoring
  labels:
    app: finmfb
    component: grafana
data:
  datasource.yml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus:9090
      access: proxy
      isDefault: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: finmfb-monitoring
  labels:
    app: finmfb
    component: grafana
data:
  dashboard.yml: |
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      updateIntervalSeconds: 10
      options:
        path: /var/lib/grafana/dashboards
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: finmfb-monitoring
  labels:
    app: finmfb
    component: grafana
type: Opaque
data:
  admin-password: R3JhZmFuYVN0cm9uZ1Bhc3N3b3JkMTIzIQ==  # GrafanaStrongPassword123! (base64 encoded)
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: finmfb-monitoring
  labels:
    app: finmfb
    component: grafana
spec:
  ports:
  - port: 3000
    targetPort: 3000
    name: http
  selector:
    app: finmfb
    component: grafana