apiVersion: v1
kind: ResourceQuota
metadata:
  name: finmfb-quota
  namespace: finmfb
spec:
  hard:
    limits.cpu: "16"
    limits.memory: 16Gi
    requests.cpu: "8"
    requests.memory: 8Gi
    pods: "30"
    services: "15"
    persistentvolumeclaims: "10"
    secrets: "20"
    configmaps: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: finmfb-limits
  namespace: finmfb
spec:
  limits:
  - default:
      memory: 512Mi
      cpu: 500m
    defaultRequest:
      memory: 256Mi
      cpu: 200m
    type: Container