apiVersion: v1
kind: Secret
metadata:
  name: fintech-staging-secrets
  namespace: fintech-staging
type: Opaque
# Note: These are placeholder values for staging environment
data:
  db-connection-string: U3RhZ2luZ19Db25uZWN0aW9uU3RyaW5n
  redis-connection-string: cmVkaXMtc2VydmljZTo2Mzc5
  jwt-secret-key: U3RhZ2luZ19KV1RfU2VjcmV0X0tleQ==
  rabbitmq-username: c3RhZ2luZ3VzZXI=
  rabbitmq-password: c3RhZ2luZ3Bhc3M=
  rabbitmq-erlang-cookie: U3RhZ2luZ19FcmxhbmdfQ29va2ll
---
apiVersion: v1
kind: Secret
metadata:
  name: github-container-registry
  namespace: fintech-staging
type: kubernetes.io/dockerconfigjson
data:
  # This is a placeholder
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiZ2l0aHViLXVzZXIiLCJwYXNzd29yZCI6ImdpdGh1Yi10b2tlbiIsImF1dGgiOiJaMmwwYUhWaUxYVnpaWEk2WjJsMGFIVmlMWFJ2YTJWdSJ9fX0=
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-auth
  namespace: fintech-staging
type: Opaque
data:
  # Basic auth for RabbitMQ management UI - staging/stagingpass
  auth: c3RhZ2luZzokYXByMSRIMUZ4YkZNdiRtbDRneTlnS2JrWTVldUlSY3l2ZFUx
---
# Create namespace if it doesn't exist
apiVersion: v1
kind: Namespace
metadata:
  name: fintech-staging
  labels:
    name: fintech-staging
    environment: staging
---
# Network policies for staging environment
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: fintech-backend-network-policy
  namespace: fintech-staging
spec:
  podSelector:
    matchLabels:
      app: fintech-backend
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: fintech-staging
    - podSelector:
        matchLabels:
          app: fintech-frontend
    ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 443
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: redis
    ports:
    - protocol: TCP
      port: 6379
  - to:
    - podSelector:
        matchLabels:
          app: rabbitmq
    ports:
    - protocol: TCP
      port: 5672
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: fintech-frontend-network-policy
  namespace: fintech-staging
spec:
  podSelector:
    matchLabels:
      app: fintech-frontend
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 80
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: fintech-backend
    ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 443
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP