apiVersion: apps/v1
kind: Deployment
metadata:
  name: fintech-backend
  namespace: fintech-prod
  labels:
    app: fintech-backend
    environment: production
spec:
  replicas: 5
  selector:
    matchLabels:
      app: fintech-backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: fintech-backend
        environment: production
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
        prometheus.io/path: "/metrics"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - fintech-backend
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: fintech-backend
        image: ghcr.io/opius2017/finmfb/fintech-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: fintech-prod-secrets
              key: db-connection-string
        - name: ConnectionStrings__Redis
          valueFrom:
            secretKeyRef:
              name: fintech-prod-secrets
              key: redis-connection-string
        - name: JwtSettings__Key
          valueFrom:
            secretKeyRef:
              name: fintech-prod-secrets
              key: jwt-secret-key
        - name: JwtSettings__Issuer
          value: "FinTechAPI.Prod"
        - name: JwtSettings__Audience
          value: "FinTechClient.Prod"
        - name: JwtSettings__DurationInMinutes
          value: "15"
        - name: RabbitMQ__Host
          value: "rabbitmq-service"
        - name: RabbitMQ__Port
          value: "5672"
        - name: RabbitMQ__Username
          valueFrom:
            secretKeyRef:
              name: fintech-prod-secrets
              key: rabbitmq-username
        - name: RabbitMQ__Password
          valueFrom:
            secretKeyRef:
              name: fintech-prod-secrets
              key: rabbitmq-password
        resources:
          limits:
            cpu: "4"
            memory: "4Gi"
          requests:
            cpu: "2"
            memory: "2Gi"
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health/live
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
        startupProbe:
          httpGet:
            path: /health/live
            port: 80
          failureThreshold: 30
          periodSeconds: 10
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
        - name: log-volume
          mountPath: /app/logs
      volumes:
      - name: tmp-volume
        emptyDir: {}
      - name: log-volume
        persistentVolumeClaim:
          claimName: fintech-backend-logs-pvc
      imagePullSecrets:
      - name: github-container-registry
---
apiVersion: v1
kind: Service
metadata:
  name: fintech-backend
  namespace: fintech-prod
  labels:
    app: fintech-backend
    environment: production
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app: fintech-backend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fintech-backend-ingress
  namespace: fintech-prod
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  tls:
  - hosts:
    - api.finmfb.com
    secretName: fintech-backend-prod-tls
  rules:
  - host: api.finmfb.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fintech-backend
            port:
              number: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fintech-backend-hpa
  namespace: fintech-prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fintech-backend
  minReplicas: 5
  maxReplicas: 15
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 25
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 50
        periodSeconds: 30
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fintech-backend-logs-pvc
  namespace: fintech-prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard